In [ ]:
import pandas as pd

df=pd.read_csv('/content/academic_performance_students_raw.csv')
display(df.head(10))

,Student_ID,Name,Age,Gender,Attendance_%,Math,Science,English,Final_Result
0,1001,Student_1,20.0,F,37,32.0,44.0,95.0,Fail
1,1002,Student_2,21.0,F,8,93.0,31.0,66.0,Fail
2,1003,Student_3,19.0,F,-7,100.0,44.0,26.0,Fail
3,1004,Student_4,21.0,M,24,22.0,60.0,92.0,Pass
4,1005,Student_5,21.0,F,53,9.0,46.0,31.0,Fail
5,1006,Student_6,18.0,M,38,68.0,20.0,49.0,Pass
6,1007,Student_7,19.0,F,6,99.0,79.0,60.0,Pass
7,1008,Student_8,19.0,M,33,33.0,84.0,50.0,Fail
8,1009,Student_9,19.0,F,81,51.0,74.0,18.0,Fail
9,1010,Student_10,21.0,F,19,94.0,100.0,20.0,Pass

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    200 non-null    int64
 1   Name          200 non-null    object
 2   Age           168 non-null    float64
 3   Gender        200 non-null    object
 4   Attendance_%  200 non-null    int64
 5   Math          199 non-null    float64
 6   Science       198 non-null    float64
 7   English       199 non-null    float64
 8   Final_Result  200 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 14.2+ KB

In [ ]:
#To get the descriptive statistics for all numerical columns
df.describe()

,Student_ID,Age,Attendance_%,Math,Science,English
count,200.000000,168.000000,200.000000,199.000000,198.000000,199.000000
mean,1100.500000,19.065476,51.575000,48.814070,50.661616,48.211055
std,57.879185,1.406315,34.911581,30.120475,30.007134,30.757699
min,1001.000000,17.000000,-10.000000,0.000000,0.000000,0.000000
25%,1050.750000,18.000000,21.000000,22.500000,25.000000,21.000000
50%,1100.500000,19.000000,49.500000,45.000000,52.000000,48.000000
75%,1150.250000,20.000000,83.000000,74.000000,76.000000,74.000000
max,1200.000000,21.000000,109.000000,100.000000,100.000000,100.000000

In [ ]:
#Unique Values of  Gender and its counts
df['Gender'].value_counts()

Gender
F    109
M     91
Name: count, dtype: int64

In [ ]:
#Unique Values of Final_Result and its Counts
df['Final_Result'].value_counts()

Final_Result
Pass    103
Fail     97
Name: count, dtype: int64

In [ ]:
#Unique Values of Name and its counts
df['Name'].value_counts()

Name
Student_1      1
Student_2      1
Student_3      1
Student_4      1
Student_5      1
              ..
Student_196    1
Student_197    1
Student_198    1
Student_199    1
Student_200    1
Name: count, Length: 200, dtype: int64

In [ ]:
#Correcting invalid 'Attendance_%' values
#Set negative attendance to 0
df.loc[df['Attendance_%']<0,'Attendance_%']=0

#Set Attendance greater than 100 to be 100
df.loc[df['Attendance_%']>100,'Attendance_%']=100

#Verification
display(df['Attendance_%'].describe())

count    200.000000
mean      51.495000
std       33.600371
min        0.000000
25%       21.000000
50%       49.500000
75%       83.000000
max      100.000000
Name: Attendance_%, dtype: float64

In [ ]:
#Imputation of Age,Math,Science and English
#Impute missing Age and the subject  values with the mean

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Math'] = df['Math'].fillna(df['Math'].mean())
df['Science'] = df['Science'].fillna(df['Science'].mean())
df['English'] = df['English'].fillna(df['English'].mean())

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    200 non-null    int64
 1   Name          200 non-null    object
 2   Age           200 non-null    float64
 3   Gender        200 non-null    object
 4   Attendance_%  200 non-null    int64
 5   Math          200 non-null    float64
 6   Science       200 non-null    float64
 7   English       200 non-null    float64
 8   Final_Result  200 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 14.2+ KB

In [ ]:
df.describe()

,Student_ID,Age,Attendance_%,Math,Science,English
count,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000
mean,1100.500000,19.065476,51.495000,48.81407,50.661616,48.211055
std,57.879185,1.288292,33.600371,30.04470,29.855963,30.680321
min,1001.000000,17.000000,0.000000,0.00000,0.000000,0.000000
25%,1050.750000,18.000000,21.000000,22.75000,25.000000,21.000000
50%,1100.500000,19.065476,49.500000,46.50000,51.500000,48.105528
75%,1150.250000,20.000000,83.000000,74.00000,76.000000,74.000000
max,1200.000000,21.000000,100.000000,100.00000,100.000000,100.000000

In [ ]:
#Convert Gender and Final Result to category data type
df['Gender']=df['Gender'].astype('category')
df['Final_Result']=df['Final_Result'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    200 non-null    int64
 1   Name          200 non-null    object
 2   Age           200 non-null    float64
 3   Gender        200 non-null    category
 4   Attendance_%  200 non-null    int64
 5   Math          200 non-null    float64
 6   Science       200 non-null    float64
 7   English       200 non-null    float64
 8   Final_Result  200 non-null    category
dtypes: category(2), float64(4), int64(2), object(1)
memory usage: 11.7+ KB

In [ ]:
#Apply one hot encoding to Gender and Final Result
#drop_first=True is used to avoid multicollinearity for binary variables
df=pd.get_dummies(df,columns=['Gender','Final_Result'],drop_first=True)
display(df.head())

,Student_ID,Name,Age,Attendance_%,Math,Science,English,Gender_M,Final_Result_Pass
0,1001,Student_1,20.0,37,32.0,44.0,95.0,False,False
1,1002,Student_2,21.0,8,93.0,31.0,66.0,False,False
2,1003,Student_3,19.0,0,100.0,44.0,26.0,False,False
3,1004,Student_4,21.0,24,22.0,60.0,92.0,True,True
4,1005,Student_5,21.0,53,9.0,46.0,31.0,False,False

In [ ]:
from sklearn.preprocessing import MinMaxScaler

#Initialize the MinMaxScaler
scaler=MinMaxScaler()

#List of numerical columns to scale
numerical_cols=['Age','Attendance_%','Math','Science','English']

#Apply the MinMax scaling to the selected numerical columns
df[numerical_cols]=scaler.fit_transform(df[numerical_cols])

df.head()

,Student_ID,Name,Age,Attendance_%,Math,Science,English,Gender_M,Final_Result_Pass
0,1001,Student_1,0.75,0.37,0.32,0.44,0.95,False,False
1,1002,Student_2,1.00,0.08,0.93,0.31,0.66,False,False
2,1003,Student_3,0.50,0.00,1.00,0.44,0.26,False,False
3,1004,Student_4,1.00,0.24,0.22,0.60,0.92,True,True
4,1005,Student_5,1.00,0.53,0.09,0.46,0.31,False,False

In [ ]:
df.describe()

,Student_ID,Age,Attendance_%,Math,Science,English
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,1100.500000,0.516369,0.514950,0.488141,0.506616,0.482111
std,57.879185,0.322073,0.336004,0.300447,0.298560,0.306803
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1050.750000,0.250000,0.210000,0.227500,0.250000,0.210000
50%,1100.500000,0.516369,0.495000,0.465000,0.515000,0.481055
75%,1150.250000,0.750000,0.830000,0.740000,0.760000,0.740000
max,1200.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
columns_to_check = ['Age', 'Math', 'Science', 'English']

In [ ]:
for column in columns_to_check:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap the outliers
    df.loc[df[column] < lower_bound, column] = lower_bound
    df.loc[df[column] > upper_bound, column] = upper_bound

df.describe()

,Student_ID,Age,Attendance_%,Math,Science,English
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,1100.500000,0.516369,0.514950,0.488141,0.506616,0.482111
std,57.879185,0.322073,0.336004,0.300447,0.298560,0.306803
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1050.750000,0.250000,0.210000,0.227500,0.250000,0.210000
50%,1100.500000,0.516369,0.495000,0.465000,0.515000,0.481055
75%,1150.250000,0.750000,0.830000,0.740000,0.760000,0.740000
max,1200.000000,1.000000,1.000000,1.000000,1.000000,1.000000